import time
from tkinter import *
def get_data():
    final_window.deiconify()
    root.withdraw()
    final_label = Label(final_window, text= f"The company is registrated to {input1.get()} {input2.get()}. The name is {input3.get()} and it has a capital of {input4.get()}$")
    final_label.pack()
root = Tk()
root.title("REGISTRATION")
root.geometry("400x200")
final_window = Tk()
final_window.title("RESULT")
final_window.withdraw()
label = Label(text= "                                    COMPANY REGISTRATION                                  ")
label.pack()
label1 = Label(text= "FIRST NAME")
label1.pack()
input1 = Entry(root)
input1.pack()
label2 = Label(root, text= "LAST NAME")
label2.pack()
input2 = Entry(root)
input2.pack()
label3 = Label(root, text= "COMPANY NAME")
label3.pack()
input3 = Entry(root)
input3.pack()
label4 = Label(root, text= "CAPITAL")
label4.pack()
input4 = Entry(root)
input4.pack()
button1 = Button(root, text= "REGISTRATE", command=get_data)
button1.pack()
root.mainloop()